from web_attendance import app,db
from flask import render_template, flash, redirect,session, request
from web_attendance.forms import *
from web_attendance.models import *
import datetime,copy
from datetime import timedelta
from werkzeug.datastructures import MultiDict
import sys

#subject_list = ['DSC','DSC LAB','CODE','CODE LAB','OS','OS LAB','DMS','MATHS','BT','KANNADA','']
subject_list = ['DAA','DAA LAB','MCES','MCES LAB','OOP','OOP LAB','CN','GRAPH','BT','DTL']
subject_list.append('')
sub_choice_list = []
for i in range(len(subject_list)):
    sub_choice_list.append((str(i),subject_list[i]))  
     #[('0','DSC),('1','DSC LAB)....]

status_choice_list = [('C', 'Cancelled'), ('P', 'Present'), ('A', 'Absent'), ('N', 'Not Scheduled on this day')]

Class_attr_list = []
status_attr_list = [] 
sql_status_attr_list = []
      
for num in ['first','second','third','fourth','fifth','sixth']:
    Class_attr_list.append(num+"_class")
    status_attr_list.append(num+"_class_status")
    sql_status_attr_list.append(num+"_status")      
    #sql column names are different i.e. first_class_status vs first_status




'''time_table = [['DSC','DMS','OS','BT','CODE LAB'],
              ['OS','CODE','OS LAB','MATHS','DSC'],
              ['DMS','MATHS','BT','CODE','MATHS','KANNADA'],
              ['DSC LAB','MATHS','CODE','CODE'],
              ['MATHS','DSC','DMS','OS']]
'''
time_table = [['OOP','MCES','GRAPH','DAA','DTL'],
              ['GRAPH','DAA','OOP LAB','CN','BT'],
              ['CN','GRAPH','MCES LAB','GRAPH'],
              ['MCES','CN','GRAPH','OOP','DAA LAB'],
              ['DAA','OOP','BT','MCES','DTL']]
              
            

for x in time_table:
    for y in x:
        if y not in subject_list:
            print("There is an entry in time table that does not match any entry in subject_list. Please check the time table again.")
            sys.exit()
            
            
def special_print(final_list):
    #To print the list generated by dict_union
    final_str = ''
    for inner in final_list:
        for element in inner:
            if type(element) == datetime.date:  
                #I don't want to print date in yy-mm-dd as is default in the __str__ attribute of datetime type
                #print(element.strftime('%d-%m-%y'),end = '\t')
                final_str = final_str + element.strftime('%d-%m-%y') + '\t'
                
            else:
                #print(element,end = '\t')
                final_str = final_str + element.ljust(22)
        #print('\n')
        final_str = final_str + '\n'
    return final_str

def nestrepl(lst, what, repl):    
    #to recursively(deep) replace all occurrences of the element 'what' with the element 'repl' in a nested list 'lst', modifies lst without any return value
    
    for index, item in enumerate(lst):
        if type(item) == list:
            nestrepl(item, what, repl)
        else:
            if item == what:
                lst[index] = repl
              
def substract(a, b):    
    #to return a-b where a and b are two strings without modifying a and b                         
    return "".join(a.rsplit(b))
    
def substitute(my_list,old_element,new_element):
    #Stupid version of nestrepl; shallow replaces in a new list leaving the original list unmodified
    my_new_list = [new_element if x==old_element else x for x in my_list]
    return my_new_list

def def_stat(sub):
    #To decide if 'N' or 'C' must be the preset attendance value in the form
    if sub==str(len(subject_list)-1):         
        #if subject is the last element of the subject list('None') then default status is N(Not Scheduled)
        return 'N'
    else:
        return 'C'





def select_sub_no(this_date,field):
    #determines subject and hence returns its subject index(in subject_list) based on the time table given date string,field('12-08-19','first_class')
    day_num = datetime.datetime.strptime(this_date,'%d-%m-%Y').strftime('%w')   #0 is sunday 6 is saturday for %w
        
    class_index = int(Class_attr_list.index(field))
    
    try:
        subject = time_table[int(day_num)-1][class_index]
    except IndexError:
        subject =  ""
    
    subject_no = int(subject_list.index(subject))
    return subject_no

def get_default_date():
    #returns date string succeeding last entered date value in the database; calls date_increment function to increment last date string
    a = db.session.query(Attendance).order_by(db.asc(Attendance.date)).all()
 
    print("QUERY a is {} of length {}".format(str(a),len(a)))

    if len(a) == 0:
        default_date = "01-08-2019"
    else:
        print("DATE FETCHED FROM DATABASE")
        yesterday_date_obj = a[-1].date
        yesterday_date = str(yesterday_date_obj.strftime("%d-%m-%Y"))
        default_date = str(date_increment(yesterday_date))

    return default_date

def date_increment(date_str):
    #converts date string into date object; increments it using timedelta; converts it back to a string and returns it
    dt_obj = datetime.datetime.strptime(date_str,'%d-%m-%Y').date()
    if dt_obj.strftime('%A')=='Friday':
        new_dt_obj = dt_obj + timedelta(days=3)
    else:
        new_dt_obj = dt_obj + timedelta(days=1)   
    return new_dt_obj.strftime('%d-%m-%Y')
    
def process_list(a):
    #calculates attendance stats from list of statuses; ['p','p','A','N','p'.......]
    present = 0
    absent = 0
    for value in a:
        if value=='P':
            present+=1
        elif value=='A':
            absent+=1
    total = present + absent
    if total==0:
        att = 0
    else:
        att = (float(present)/total) * 100
    att = round(att,3)
    if att<80.0:
        clr = "red"
    else:
        clr = "black"
    return [present,total,clr,att]
    
def combine(dict1,dict2):
    #combines data dictionaries of theory and lab subjects of a subject comprising of both and returns the combined dictionary
    #WEIGHTING_FACTOR = [1,1,1]
    new_dict = {}
    new_dict['subject'] = subject = dict1['subject'] + ' COMBINED'
    new_dict['classes_present'] = present = int(dict1['classes_present'])+int(dict2['classes_present'])
    new_dict['total_classes'] = total = int(dict1['total_classes'])+int(dict2['total_classes'])
    if total==0:
        att = 0
    else:
        att = (float(present)/total) * 100
    att = round(att,3)
    if att<80.0:
        clr = "red"
    else:
        clr = "black"
    new_dict['attendance'] = att
    new_dict['colour'] = clr
    new_dict['this_link'] = "/details?subject="+(subject.replace(" ","_"))
    print("hello")
    return new_dict

    
    
def combine_lab(initial_list):
    #Takes a list of data dictionaries as arguments; checks if consecutive dictionaries belong to the same subject; calls combine of the two dictionaries; inserts it into a new list of data dicts that is returned
    final_list = copy.deepcopy(initial_list)
    for i in range(len(initial_list)-1):
        if initial_list[i+1]['subject'] == (initial_list[i]['subject'] + " LAB"):
            #print("CONDITION SATISFIED")
            new_dict = combine(initial_list[i],initial_list[i+1])
            final_list.insert((final_list.index(initial_list[i+1])+1),new_dict)
    print(final_list)
    return final_list
 
 
    
def get_attendance_report():
    #queries database to get status list for each subject; processes the status list 
    full_list = []
    for subject in subject_list:
        subject_dict = {}
        status_list = []
        for (class_num,status_num) in zip(Class_attr_list,sql_status_attr_list):
            a = db.session.query(getattr(Attendance,status_num)).filter(getattr(Attendance,class_num)==subject).all()
            for (status,) in a:
                status_list.append(status)
        subject_dict['subject'] = subject
        other_dict_values = process_list(status_list)
        subject_dict['classes_present'] = other_dict_values[0]
        subject_dict['total_classes'] = other_dict_values[1]
        subject_dict['colour'] = other_dict_values[2]
        subject_dict['attendance'] = other_dict_values[3]
        subject_dict['this_link'] = "/details?subject="+(subject.replace(" ","_"))
        full_list.append(subject_dict)
        
    final_list = combine_lab(full_list)
    return final_list
            
            
            
    
    

def add_into_database(subl,statl,com,ds):
    dt_obj = datetime.datetime.strptime(ds,'%d-%m-%Y').date()
    dsn = datetime.datetime.strptime(ds,'%d-%m-%Y').strftime('%Y-%m-%d')
    a = db.session.query(Attendance).filter(Attendance.date==dt_obj).all()   
    print("DIR a = ",dir(a)) 
    combined_list = []
    
    #for this_subl, this_statl in zip(subl, statl):
    #    combined_list.extend(this_subl, this_statl)
  
    
    
    
    for j in range(len(subl)):
        combined_list.extend((subl[j],statl[j]))
    combined_list.append(com)
    combined_list = substitute(combined_list,'','None')
    print("COMBINED LIST = ",combined_list)
    queries_list = []
    if len(a)!=0:
        i = 0
        columns_list = list(Attendance.__table__.columns.keys())
        columns_list = columns_list[1:]    #remove date in updation statement
        print(columns_list)
        
        
        for field in columns_list:
            print("THIS FIELD = ",field)
            my_query  = "update attendance set "+field+"='"+combined_list[i]+"' where date='"+dsn+"';"
            queries_list.append(my_query)
            i+=1

    else:
        values_list = [dsn]+combined_list
        print("VALUES LIST = ",values_list)
        values_str = "('"+"','".join(values_list)+"')"
        my_query = "insert into attendance values "+values_str+";"
        queries_list = [my_query]
        
    print("QUERIES LIST = ",queries_list)
        
    with db.engine.connect() as con:
        for my_query in queries_list:
            con.execute(my_query)
            

def remove_none(s):
    if s=='None':
        s = ''
    return s
    
    
def insert_position(position, list1, list2):
    return list1[:position] + list2 + list1[position:]
    
def dict_union(a):
    ret_list = []
    d = {}
    for sl in a:
        sl_tuple = (sl[0],sl[-1])
        
        if sl_tuple not in d.keys():
            d[sl_tuple] = []
        nl = sl[1:-1]
        d[sl_tuple].append(nl)
    for key,similar in d.items():
        concat_list = [j for i in similar for j in i]
        d[key] = concat_list
        main_list = list(key)
        main_list = insert_position(1,main_list,concat_list)
        ret_list.append(main_list)
        
    return ret_list
    
    

    
def get_details(sub_name):
    
    temp_list = []
    columns_list = list(Attendance.__table__.columns.keys())
    for Class in Class_attr_list:
        a = db.session.query(Attendance).filter(getattr(Attendance,Class)==sub_name).all()
        for record in a:
            short_list = [record.date,Class,getattr(record,substract(Class,"_class")+'_status'),record.comments]
            temp_list.append(short_list)
            
            
    for Class in Class_attr_list:
        a = db.session.query(Attendance).filter(getattr(Attendance,Class)==(sub_name+"_LAB")).all()
        for record in a:
            short_list = [record.date,"LAB",Class,getattr(record,substract(Class,"_class")+'_status'),record.comments]
            temp_list.append(short_list)        
       
    final_list = dict_union(temp_list)
    return final_list





@app.route('/',methods=['GET','POST'])
@app.route('/home',methods=['GET','POST'])
def home():
    return render_template('home.html')

@app.route('/date_entry',methods=['GET','POST'])
def date_entry():
    form = DateForm()
    if form.validate_on_submit():
        session['dt'] = form.date_str.data
        return redirect('/data_entry')
    else:
        print(form.errors,"\n\n\nABOVE ARE ERRORS IN DATE ENTRY FORM\n\n\n")
    default_date = get_default_date()
    form.date_str.data=default_date
    return render_template('date_entry.html',form=form)

@app.route('/data_entry',methods=['GET','POST'])
def data_entry():
    session['sno'] = 0
    date_str=str(session['dt'])

    dt_obj = datetime.datetime.strptime(date_str,'%d-%m-%Y').date()
    last_comment = ''
    default_value_list = []
    default_status_list = []
    res = db.session.query(Attendance).filter(Attendance.date==dt_obj).all()
    
    
    if len(res):
        row = res[0]
        qq = subject_list.index(row.first_class)
        default_value_list.append(str(subject_list.index(remove_none(row.first_class))))
        default_status_list.append(row.first_status)
        default_value_list.append(str(subject_list.index(remove_none(row.second_class))))
        default_status_list.append(row.second_status)
        default_value_list.append(str(subject_list.index(remove_none(row.third_class))))
        default_status_list.append(row.third_status)
        default_value_list.append(str(subject_list.index(remove_none(row.fourth_class))))
        default_status_list.append(row.fourth_status)
        default_value_list.append(str(subject_list.index(remove_none(row.fifth_class))))
        default_status_list.append(row.fifth_status)
        default_value_list.append(str(subject_list.index(remove_none(row.sixth_class))))
        default_status_list.append(row.sixth_status)
        last_comment = row.comments

        
    
    else:
        for field in Class_attr_list:
            default_value_list.append(str(select_sub_no(date_str,field)))
            default_status_list.append(def_stat(str(select_sub_no(date_str,field))))
    
   
            
    if request.method == 'GET':
        form = AttendanceForm(first_class=default_value_list[0],
                              first_class_status=default_status_list[0],
                              second_class=default_value_list[1], 
                              second_class_status=default_status_list[1],
                              third_class=default_value_list[2], 
                              third_class_status=default_status_list[2],
                              fourth_class=default_value_list[3],
                              fourth_class_status=default_status_list[3],
                              fifth_class=default_value_list[4], 
                              fifth_class_status=default_status_list[4],
                              sixth_class=default_value_list[5],
                              sixth_class_status=default_status_list[5],
                              formdata=MultiDict({'comments':last_comment})
                              )
        
    else:
        form = AttendanceForm(first_class=default_value_list[0],
                              first_class_status=default_status_list[0],
                              second_class=default_value_list[1], 
                              second_class_status=default_status_list[1],
                              third_class=default_value_list[2], 
                              third_class_status=default_status_list[2],
                              fourth_class=default_value_list[3],
                              fourth_class_status=default_status_list[3],
                              fifth_class=default_value_list[4], 
                              fifth_class_status=default_status_list[4],
                              sixth_class=default_value_list[5],
                              sixth_class_status=default_status_list[5]
                              )
    
    
    for field in Class_attr_list:
        getattr(form,field).choices = sub_choice_list

    for field in status_attr_list:
        getattr(form,field).choices = status_choice_list
        
    attr_tup_list = [(Class_attr_list[i],status_attr_list[i]) for i in range(6)]  
    #6 hours per day 

    if form.validate_on_submit():
        subject_data_list = []
        status_data_list = []
        
        
        for (a,b) in attr_tup_list:
            subject_data_list.append(subject_list[int(getattr(form,a).data)])
            status_data_list.append(str(getattr(form,b).data))
            
        comment_data = form.comments.data
        add_into_database(subject_data_list,status_data_list,comment_data,date_str)
        return redirect('/done')
        
        
    else:
        print(form.errors,"\n\n\nABOVE ARE ERRORS IN DATA ENTRY FORM\n\n\n")
        
           
    
    return render_template('data_entry.html',form=form, attr_tup_list=attr_tup_list,date_str=date_str,day_name = datetime.datetime.strptime(date_str,'%d-%m-%Y').strftime('%A'))

@app.route('/done',methods=['GET','POST'])
def done():
    return render_template('done.html')
    
@app.route('/attendance_status',methods=['GET','POST'])
def attendance_status():
    full_list = get_attendance_report()
    return render_template("attendance_status.html",full_list=full_list)
    
@app.route('/details',methods=['GET','POST'])
def details_getter():
    sub_name = request.args.get('subject')
    if sub_name.endswith("COMBINED"):
        sub_name = substract(sub_name,"_COMBINED")
    details_list = get_details(sub_name)
    details_list.sort(key = lambda x: x[0])
    print(details_list)
    final_str = special_print(details_list)
    print("\n\n\n---------------------------------------------------------------------------------------------------------------------------------\n\n\n\n"+final_str+"\n\n\n-------------------------------------------------------------------------------------------------------------------------------------\n\n\n\n")
    final_str = final_str.replace('\n', '<br>')
    final_str = final_str.replace('\t', '    ')
    return render_template('details.html',final_str = final_str)
    


    
    

    
