# Generated by Django 3.1.4 on 2021-03-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('class_num', models.CharField(max_length=40)),
                ('subject_name', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Attendance',
                'db_table': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=40)),
                ('class_num', models.CharField(max_length=40)),
                ('subject_name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Timetable',
                'db_table': 'Timetable',
            },
        ),
    ]
