# Generated by Django 3.1.4 on 2021-03-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('day', 'class_num')},
        ),
    ]
