# Generated by Django 3.1.4 on 2021-03-07 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20210307_0755'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'class_num')},
        ),
    ]
