# Generated by Django 3.1.4 on 2021-03-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20210307_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
